# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-19 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('std', models.IntegerField()),
                ('section', models.CharField(max_length=5)),
                ('address', models.TextField()),
            ],
        ),
    ]
